keys:
  - &users
    - &tux age14vktfes95f33vuefwnmuvryas7az04u76dsgyhfvsx73czkvmp2q7njkl4

  - &hosts
    - &canopus age1cc9phftkzcwaey2rw63m74tyxdjxxzanxphsdrhy6vwlwhgehfzq9rh6e4
    - &arcturus age1zsl5d4vj6gl3h96y5p53sq5y4vr4vtlwp727h7rp9a4xfkxm53lqrh6r50
    - &alpha age145uq9emlxqzm3wqauy9zqj78wqx9e6h09xag6wust7jjgn4upfzsaemcvx
    - &wsl age1lyvzg4ud96trsuv6gsvjw0p3rtd6qjpyl9uleq8hcrzwekuhpfesnlqauf

creation_rules:
  - path_regex: hosts/common/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *canopus
          - *arcturus
          - *alpha
          - *wsl
  - path_regex: hosts/canopus/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *canopus
  - path_regex: hosts/controller/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *arcturus
  - path_regex: hosts/alpha/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *alpha
  - path_regex: hosts/wsl/secrets.yaml$
    key_groups:
      - age:
          - *tux
          - *wsl
